-- Migration: 0002_fix_primary_goal_check
-- Applied via: pnpm --filter @workspace/db run push
-- Date: 2026-03-28
-- Purpose: Add anemia_recovery + muscle_gain/child_growth aliases to primary_goal_override CHECK.
-- 0001 was missing anemia_recovery; normalizeGoal() in profile-rules.ts maps UI aliases before
-- write, so muscle_gain and child_growth never reach the DB, but anemia_recovery does pass through.

DO $$
BEGIN
  -- Drop old CHECK constraint (name auto-generated by Postgres from table+column)
  -- We use a conditional drop so this is idempotent.
  ALTER TABLE family_members
    DROP CONSTRAINT IF EXISTS family_members_primary_goal_override_check;

  -- Re-add with full canonical set including anemia_recovery
  ALTER TABLE family_members
    ADD CONSTRAINT family_members_primary_goal_override_check
    CHECK (primary_goal_override IS NULL OR primary_goal_override IN (
      'weight_loss','weight_gain','build_muscle',
      'manage_diabetes','heart_health','manage_thyroid',
      'childhood_nutrition','general_wellness','anemia_recovery',
      'maintain','healthy_growth','senior_nutrition'
    ));
END $$;
